# Generated by Django 3.0.3 on 2020-03-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_checklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckListHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='CheckList',
        ),
    ]
