# Generated by Django 3.0.3 on 2020-03-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200326_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckListEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.TextField()),
            ],
        ),
    ]
