# Generated by Django 3.0.3 on 2020-03-27 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_checklistentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckListEntry',
        ),
    ]
