# Generated by Django 3.0.3 on 2020-03-27 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_delete_checklistentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckListEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.TextField()),
                ('checklistheader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.CheckListHeader')),
            ],
        ),
    ]
