# Generated by Django 3.0.3 on 2020-04-01 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_checklistentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistentry',
            old_name='entry',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='checklistheader',
            old_name='header',
            new_name='name',
        ),
    ]
