# Generated by Django 3.0.3 on 2020-04-02 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200402_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistentry',
            name='checklistheader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_key', to='projects.CheckListHeader'),
        ),
    ]
