# Generated by Django 3.0.3 on 2020-04-04 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200402_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('checklistheader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subheader_key', to='projects.CheckListHeader')),
            ],
        ),
        migrations.CreateModel(
            name='RefLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('subheader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_key', to='projects.SubHeader')),
            ],
        ),
    ]
