# Generated by Django 3.0.3 on 2020-04-04 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_reflinks_subheader'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefLinks',
        ),
    ]
