# Generated by Django 3.0.3 on 2020-04-04 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_delete_reflinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('subheader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_key', to='projects.SubHeader')),
            ],
        ),
    ]
