# Generated by Django 3.0.3 on 2020-04-04 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_reflink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subheader',
            name='checklistheader',
        ),
        migrations.DeleteModel(
            name='RefLink',
        ),
        migrations.DeleteModel(
            name='SubHeader',
        ),
    ]
