# Generated by Django 3.0.3 on 2020-04-04 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20200404_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('checklistheader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subheader_key', to='projects.CheckListHeader')),
            ],
        ),
        migrations.CreateModel(
            name='RefLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('linkheader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_key', to='projects.LinkHeader')),
            ],
        ),
    ]
