# Generated by Django 3.0.3 on 2020-04-04 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_linkheader_reflink_subheader'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefLink',
        ),
    ]
