# Generated by Django 3.0.3 on 2020-04-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_reflink'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistheader',
            name='indexkey',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
