# Generated by Django 3.0.3 on 2020-04-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_checklistheader_indexkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextBodies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
