# Generated by Django 3.0.3 on 2020-04-04 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20200404_1841'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextBodies',
            new_name='TextBody',
        ),
    ]
