# Generated by Django 3.0.3 on 2020-04-05 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20200404_1842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextBody',
        ),
    ]
