# Generated by Django 3.0.3 on 2020-04-05 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_delete_textbody'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('paragraph', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_key', to='projects.Project')),
            ],
        ),
    ]
