# Generated by Django 3.0.3 on 2020-04-05 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_textbody_index_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_key', models.IntegerField()),
                ('header', models.CharField(max_length=100)),
                ('paragraph', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_key', to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_key', models.IntegerField()),
                ('header', models.CharField(max_length=100)),
                ('paragraph', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_key', to='projects.Project')),
            ],
        ),
        migrations.DeleteModel(
            name='TextBody',
        ),
    ]
