# Generated by Django 3.0.3 on 2020-04-05 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20200405_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_key', models.IntegerField()),
                ('name', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_key', to='projects.Project')),
            ],
        ),
    ]
