# Generated by Django 3.0.3 on 2020-04-05 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_projectlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDescriptionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_key', models.IntegerField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSummaryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_key', models.IntegerField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='projectdescription',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='projectsummary',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.DeleteModel(
            name='ProjectListItem',
        ),
        migrations.AddField(
            model_name='projectsummarylist',
            name='projectsummary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_key', to='projects.ProjectSummary'),
        ),
        migrations.AddField(
            model_name='projectdescriptionlist',
            name='projectdescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_key', to='projects.ProjectDescription'),
        ),
    ]
