# Generated by Django 3.0.3 on 2020-04-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_auto_20200405_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.TextField(default='blank'),
            preserve_default=False,
        ),
    ]
