# Generated by Django 3.0.3 on 2020-04-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='header',
            field=models.CharField(default='Default Header', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='index_key',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
