# Generated by Django 3.0.3 on 2020-04-07 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_auto_20200406_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_first', models.CharField(max_length=100)),
                ('name_last', models.CharField(max_length=100)),
                ('my_title', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('background', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('adminuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.PortfolioInfo')),
            ],
        ),
    ]
