# Generated by Django 3.0.3 on 2020-04-07 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_portfolioinfo_portfolioskill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioskill',
            old_name='adminuser',
            new_name='person',
        ),
    ]
