# Generated by Django 3.0.3 on 2020-05-13 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_iconskill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
