# Generated by Django 3.0.3 on 2020-05-13 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_delete_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestObject',
        ),
    ]
