# Generated by Django 3.0.3 on 2020-05-21 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_delete_testobject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IconSkill',
        ),
    ]
